services:

  auth-service:
    build:
      context: .
      dockerfile: AuthService.Presentation/Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PORT: 8080
    networks:
      - biotech-network

  commercial-service:
    build:
      context: .
      dockerfile: CommercialService.Presentation/Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PORT: 8080
    networks:
      - biotech-network

  feeding-service:
    build:
      context: .
      dockerfile: FeedingService.Presentation/Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PORT: 8080
    networks:
      - biotech-network

  health-service:
    build:
      context: .
      dockerfile: HealthService.Presentation/Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PORT: 8080
    networks:
      - biotech-network

  herd-service:
    build:
      context: .
      dockerfile: HerdService.Presentation/Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PORT: 8080
    networks:
      - biotech-network

  inventory-service:
    build:
      context: .
      dockerfile: InventoryService.Presentation/Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PORT: 8080
    networks:
      - biotech-network

  reproduction-service:
    build:
      context: .
      dockerfile: ReproductionService.Presentation/Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PORT: 8080
    networks:
      - biotech-network

  ai-service:
    build:
      context: .
      dockerfile: AIService.Presentation/Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PORT: 8080
      ServiceUrls__HerdService: http://herd-service:8080
      ServiceUrls__HealthService: http://health-service:8080
      ServiceUrls__FeedingService: http://feeding-service:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - biotech-network

  api-gateway:
    build:
      context: .
      dockerfile: ApiGateWay/Dockerfile
    ports:
      - "5000:8080"
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PORT: 8080
      AUTH_SERVICE_HOST: auth-service
      AUTH_SERVICE_PORT: 8080
      FEEDING_SERVICE_HOST: feeding-service
      FEEDING_SERVICE_PORT: 8080
      HEALTH_SERVICE_HOST: health-service
      HEALTH_SERVICE_PORT: 8080
      HERD_SERVICE_HOST: herd-service
      HERD_SERVICE_PORT: 8080
      REPRODUCTION_SERVICE_HOST: reproduction-service
      REPRODUCTION_SERVICE_PORT: 8080
      COMMERCIAL_SERVICE_HOST: commercial-service
      COMMERCIAL_SERVICE_PORT: 8080
      INVENTORY_SERVICE_HOST: inventory-service
      INVENTORY_SERVICE_PORT: 8080
    depends_on:
      - auth-service
      - feeding-service
      - herd-service
      - health-service
      - reproduction-service
      - commercial-service
      - inventory-service
    networks:
      - biotech-network

networks:
  biotech-network:
    driver: bridge
