// <auto-generated />
using System;
using CommercialService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommercialService.Infrastructure.Migrations
{
    [DbContext(typeof(CommercialDbContext))]
    [Migration("20260107032355_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommercialService.Domain.Entities.CommercialTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Discounts")
                        .HasColumnType("numeric")
                        .HasColumnName("discounts");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer")
                        .HasColumnName("farm_id");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<decimal?>("NetTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("net_total");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_status");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("registered_at");

                    b.Property<int?>("RegisteredBy")
                        .HasColumnType("integer")
                        .HasColumnName("registered_by");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("numeric")
                        .HasColumnName("taxes");

                    b.Property<long?>("ThirdPartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("third_party_id");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.ToTable("commercial_transactions", (string)null);
                });

            modelBuilder.Entity("CommercialService.Domain.Entities.ThirdParty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer")
                        .HasColumnName("farm_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentityDocument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_document");

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_customer");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("boolean")
                        .HasColumnName("is_employee");

                    b.Property<bool>("IsSupplier")
                        .HasColumnType("boolean")
                        .HasColumnName("is_supplier");

                    b.Property<bool>("IsVeterinarian")
                        .HasColumnType("boolean")
                        .HasColumnName("is_veterinarian");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("FarmId", "IdentityDocument")
                        .IsUnique();

                    b.ToTable("third_parties", (string)null);
                });

            modelBuilder.Entity("CommercialService.Domain.Entities.TransactionAnimalDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnimalId")
                        .HasColumnType("bigint")
                        .HasColumnName("animal_id");

                    b.Property<long?>("AnimalMovementId")
                        .HasColumnType("bigint")
                        .HasColumnName("animal_movement_id");

                    b.Property<decimal>("BaseHeadPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("base_head_price");

                    b.Property<decimal>("CommissionCost")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_cost");

                    b.Property<decimal?>("FinalLineValue")
                        .HasColumnType("numeric")
                        .HasColumnName("final_line_value");

                    b.Property<decimal?>("PricePerKilo")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_kilo");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    b.Property<decimal>("TransportCost")
                        .HasColumnType("numeric")
                        .HasColumnName("transport_cost");

                    b.Property<decimal?>("WeightAtNegotiation")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_at_negotiation");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("transaction_animal_details", (string)null);
                });

            modelBuilder.Entity("CommercialService.Domain.Entities.TransactionProductDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("InventoryMovementId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_movement_id");

                    b.Property<decimal?>("LineSubtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("line_subtotal");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("transaction_product_details", (string)null);
                });

            modelBuilder.Entity("CommercialService.Domain.Entities.TransactionAnimalDetail", b =>
                {
                    b.HasOne("CommercialService.Domain.Entities.CommercialTransaction", "Transaction")
                        .WithMany("AnimalDetails")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("CommercialService.Domain.Entities.TransactionProductDetail", b =>
                {
                    b.HasOne("CommercialService.Domain.Entities.CommercialTransaction", "Transaction")
                        .WithMany("ProductDetails")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("CommercialService.Domain.Entities.CommercialTransaction", b =>
                {
                    b.Navigation("AnimalDetails");

                    b.Navigation("ProductDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
