// <auto-generated />
using System;
using FeedingService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FeedingService.Infrastructure.Migrations
{
    [DbContext(typeof(FeedingDbContext))]
    [Migration("20260107032630_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FeedingService.Domain.Entities.FeedingEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AnimalId")
                        .HasColumnType("bigint")
                        .HasColumnName("animal_id");

                    b.Property<int>("AnimalsFedCount")
                        .HasColumnType("integer")
                        .HasColumnName("animals_fed_count");

                    b.Property<int?>("BatchId")
                        .HasColumnType("integer")
                        .HasColumnName("batch_id");

                    b.Property<decimal?>("CalculatedTotalCost")
                        .HasColumnType("numeric(12, 2)")
                        .HasColumnName("calculated_total_cost");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int?>("DietId")
                        .HasColumnType("integer")
                        .HasColumnName("diet_id");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer")
                        .HasColumnName("farm_id");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("RegisteredBy")
                        .HasColumnType("integer")
                        .HasColumnName("registered_by");

                    b.Property<DateTime>("SupplyDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("supply_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("numeric(12, 2)")
                        .HasColumnName("total_quantity");

                    b.Property<decimal>("UnitCostAtMoment")
                        .HasColumnType("numeric(12, 2)")
                        .HasColumnName("unit_cost_at_moment");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("ix_feeding_events_animal_id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_feeding_events_batch_id");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("ix_feeding_events_farm_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_feeding_events_product_id");

                    b.HasIndex("SupplyDate")
                        .HasDatabaseName("ix_feeding_events_supply_date");

                    b.HasIndex("FarmId", "SupplyDate")
                        .HasDatabaseName("ix_feeding_events_farm_supply_date");

                    b.ToTable("feeding_events", null, t =>
                        {
                            t.HasCheckConstraint("check_feeding_destination", "(batch_id IS NOT NULL) <> (animal_id IS NOT NULL)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
