// <auto-generated />
using System;
using HealthService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthService.Infrastructure.Migrations
{
    [DbContext(typeof(HealthServiceDbContext))]
    [Migration("20260107032550_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthService.Domain.Entities.Disease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("diseases", (string)null);
                });

            modelBuilder.Entity("HealthService.Domain.Entities.HealthEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AnimalId")
                        .HasColumnType("bigint")
                        .HasColumnName("animal_id");

                    b.Property<int?>("BatchId")
                        .HasColumnType("integer")
                        .HasColumnName("batch_id");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Disease")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("disease");

                    b.Property<decimal?>("Dosage")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("dosage");

                    b.Property<string>("DosageUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dosage_unit");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer")
                        .HasColumnName("farm_id");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("text")
                        .HasColumnName("follow_up_notes");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Medication")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("medication");

                    b.Property<DateOnly?>("NextFollowUpDate")
                        .HasColumnType("date")
                        .HasColumnName("next_follow_up_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<bool>("RequiresFollowUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_follow_up");

                    b.Property<string>("Treatment")
                        .HasColumnType("text")
                        .HasColumnName("treatment");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VeterinarianName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("veterinarian_name");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("BatchId");

                    b.HasIndex("EventDate");

                    b.HasIndex("EventType");

                    b.HasIndex("FarmId");

                    b.HasIndex("FarmId", "EventDate");

                    b.ToTable("health_events", (string)null);
                });

            modelBuilder.Entity("HealthService.Domain.Entities.HealthEventDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdministrationRoute")
                        .HasColumnType("text");

                    b.Property<decimal>("DosePerAnimal")
                        .HasColumnType("numeric");

                    b.Property<long>("HealthEventId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalQuantityDeducted")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HealthEventId");

                    b.ToTable("health_event_details", (string)null);
                });

            modelBuilder.Entity("HealthService.Domain.Entities.WithdrawalPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<long>("AnimalId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductType")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WithdrawalDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("withdrawal_periods", (string)null);
                });

            modelBuilder.Entity("HealthService.Domain.Entities.HealthEventDetail", b =>
                {
                    b.HasOne("HealthService.Domain.Entities.HealthEvent", "HealthEvent")
                        .WithMany()
                        .HasForeignKey("HealthEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HealthService.Domain.ValueObjects.Money", "CalculatedTotalCost", b1 =>
                        {
                            b1.Property<long>("HealthEventDetailId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("calculated_total_cost");

                            b1.HasKey("HealthEventDetailId");

                            b1.ToTable("health_event_details");

                            b1.WithOwner()
                                .HasForeignKey("HealthEventDetailId");
                        });

                    b.OwnsOne("HealthService.Domain.ValueObjects.Money", "UnitCostAtMoment", b1 =>
                        {
                            b1.Property<long>("HealthEventDetailId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("unit_cost_at_moment");

                            b1.HasKey("HealthEventDetailId");

                            b1.ToTable("health_event_details");

                            b1.WithOwner()
                                .HasForeignKey("HealthEventDetailId");
                        });

                    b.Navigation("CalculatedTotalCost");

                    b.Navigation("HealthEvent");

                    b.Navigation("UnitCostAtMoment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
